### ISSUE TITLE
Mention how code contributors are credited

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/Zazolc#7]
extracted from https://github.com/matkoniecz/Zazolc/issues/4 - reported by @mnalis

> should code authors be mentioned somewhere? or just authors of images (which is documented in docs)?

This is a bit in limbo, see https://github.com/streetcomplete/StreetComplete/pull/2815 Will update once situation is clear.

**Comment by mnalis** [comment]
https://github.com/streetcomplete/StreetComplete/pull/3850 might have cleared that up?
